apiVersion: apps/v1
kind: Deployment
metadata:
  name: dio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dio-app
  template:
    metadata:
      labels:
        app: dio-app
    spec:
      imagePullSecrets:
      - name: ycr-secret
      containers:
      - name: dio-app
        image: cr.yandex/crpom655acgl1rhhnucb/dio-app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
