apiVersion: v1
kind: Service
metadata:
  name: dio-app-service
spec:
  selector:
    app: dio-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # ← Фиксированный порт 30000-32767
  type: NodePort