apiVersion: v1
kind: Service
metadata:
  name: dio-app-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # kube-proxy откроет 30080 на ВСЕХ нодах
  selector:
    app: dio-app
